//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerContact2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int Hid { get; set; }
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public System.DateTime Modified { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
    }
}
