//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerContact2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerContactRelation
    {
        public int Hid { get; set; }
        public System.Guid Customer { get; set; }
        public Nullable<System.Guid> Contact { get; set; }
        public System.DateTime Created { get; set; }
    }
}
